# Generated by Django 4.2.5 on 2024-12-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'db_table': 'prefectures',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='ユーザーネーム')),
                ('family_name', models.CharField(max_length=255, verbose_name='姓')),
                ('given_name', models.CharField(max_length=255, verbose_name='名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'db_table': 'purchasers',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('building', models.CharField(blank=True, max_length=255, verbose_name='住所（建物名など）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.prefecture')),
                ('purchaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='purchase.purchaser')),
            ],
            options={
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=255, verbose_name='カード名義人')),
                ('card_number', models.CharField(max_length=16, verbose_name='カード番号')),
                ('card_expiration', models.DateField(verbose_name='有効期限')),
                ('cvv', models.CharField(max_length=3, verbose_name='セキュリティコード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('purchaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='purchase.purchaser')),
            ],
        ),
    ]
