# Generated by Django 4.2.5 on 2025-01-07 13:34

from django.db import migrations, models
import django.db.models.deletion
import purchase.varidators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_table'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaser')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_expiration',
            field=models.CharField(max_length=5, validators=[purchase.varidators.validate_expiration_date], verbose_name='有効期限'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, validators=[purchase.varidators.ValidateDigitsNumber(length=16)], verbose_name='カード番号'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=3, validators=[purchase.varidators.ValidateDigitsNumber(length=3)], verbose_name='セキュリティコード'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(max_length=7, validators=[purchase.varidators.ValidateDigitsNumber(length=7)], verbose_name='郵便番号'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('sub_total', models.IntegerField(verbose_name='小計')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchase.order')),
            ],
            options={
                'db_table': 'order_details',
                'ordering': ['created_at'],
            },
        ),
    ]
