# Generated by Django 4.2.5 on 2025-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_order_alter_creditcard_card_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='ユーザーネーム'),
        ),
    ]
