# Generated by Django 4.2.5 on 2025-01-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchaser', to='purchase.purchaser'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_detail', to='purchase.order'),
        ),
    ]
