# Generated by Django 4.2.5 on 2024-10-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imege',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像'),
        ),
    ]
