# Generated by Django 4.2.5 on 2025-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotioncode',
            table='promotion_codes',
        ),
    ]
