# Generated by Django 4.2.5 on 2025-02-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotioncode_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncode',
            options={'ordering': ['id']},
        ),
    ]
